[build]
  publish = "website"
  command = "git submodule sync && git submodule update --init || true"  
[[headers]]
  for = "/front/*.webp"
  [headers.values]
    Content-Type = "image/webp"
    Cache-Control = "public, max-age=31536000"